'use client';
import {useCallback,useEffect,useMemo,useState} from 'react';

const K={text:'#17201C',t2:'#5D6962',t3:'#8B958F',border:'#E1E5E0',teal:'#176B52',tealL:'#E9F3EE',amber:'#9A6B25',amberL:'#F8F0E3',rose:'#A44943',roseL:'#F8ECEA',plum:'#67516F',plumL:'#F0ECF2',slateL:'#EEF1EE'};
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n)||0);
const shortMoney=n=>Math.abs(Number(n)||0)>=1000?'$'+((Number(n)||0)/1000).toFixed(1)+'k':money(n);
const num=n=>Number(n)||0;
const today=()=>new Date().toISOString().slice(0,10);
const plusDays=(d,n)=>{const x=new Date(d+'T12:00:00');x.setDate(x.getDate()+n);return x.toISOString().slice(0,10)};
const fmt=d=>{if(!d)return '-';try{return new Date(String(d).slice(0,10)+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})}catch{return d}};
const invState=i=>i?.is_overdue?'Overdue':i?.status||'Unpaid';
const statusColor=s=>s==='Paid'?'#059669':s==='Partial'?K.amber:s==='Overdue'?K.rose:s==='Draft'?K.t2:K.plum;
const reorderColor=s=>s==='Overdue'?K.rose:s==='Due'?K.amber:s==='Due Soon'?K.plum:s==='Healthy'?K.teal:K.t2;

function Badge({label,color=K.t2}){return <span className="badge" style={{background:color+'18',color,border:'1px solid '+color+'28'}}>{label}</span>}
function Empty({children}){return <div style={{padding:'34px 16px',textAlign:'center',fontSize:12.5,color:K.t3}}>{children}</div>}
function Stat({label,value,sub,color=K.teal}){return <div className="card" style={{position:'relative',overflow:'hidden'}}><div style={{display:'flex',alignItems:'center',gap:7,fontSize:10,fontWeight:800,color:K.t2,textTransform:'uppercase',letterSpacing:'.075em'}}><span style={{width:7,height:7,borderRadius:'50%',background:color,boxShadow:'0 0 0 4px '+color+'12'}}/>{label}</div><div className="tnum" style={{fontSize:28,fontWeight:800,color:K.text,marginTop:12,lineHeight:1,letterSpacing:'-.04em'}}>{value}</div><div style={{fontSize:11,color:K.t3,marginTop:8}}>{sub}</div></div>}
function Field({label,children}){return <div><label>{label}</label>{children}</div>}

function InvoicePanel({invoice,items,payments,collections,onClose,onPay,onFollow}){
  if(!invoice)return null;
  const lines=items.filter(x=>x.invoice_id===invoice.id);
  const pays=payments.filter(x=>x.invoice_id===invoice.id);
  const follows=collections.filter(x=>x.invoice_id===invoice.id);
  const cases=lines.reduce((s,x)=>s+num(x.cases_sold),0);
  const gp=lines.reduce((s,x)=>s+num(x.gross_profit),0);
  return <div className="detail-panel fade" style={{width:460,maxWidth:'100vw'}}>
    <div style={{padding:'16px 20px',borderBottom:'1px solid '+K.border,display:'flex',justifyContent:'space-between',gap:12}}>
      <div><div style={{fontSize:11,color:K.t3,fontWeight:800}}>{invoice.invoice_number}</div><div style={{fontSize:18,fontWeight:900,marginTop:3}}>{invoice.account_name}</div><div style={{display:'flex',gap:7,alignItems:'center',marginTop:6,flexWrap:'wrap'}}><Badge label={invState(invoice)} color={statusColor(invState(invoice))}/><span style={{fontSize:12,color:K.t2}}>{invoice.sale_type||'Sale'} · {invoice.rep_name||'Unassigned'}</span></div></div>
      <button onClick={onClose} aria-label="Close" style={{border:'none',background:'transparent',fontSize:25,color:K.t3}}>×</button>
    </div>
    <div style={{padding:20,overflowY:'auto',flex:1}}>
      <div className="g3" style={{marginBottom:18}}>
        <div style={{padding:12,borderRadius:10,background:K.slateL}}><div style={{fontSize:10,color:K.t3,fontWeight:800}}>CASES</div><div style={{fontSize:19,fontWeight:900,marginTop:3}}>{cases}</div></div>
        <div style={{padding:12,borderRadius:10,background:K.tealL}}><div style={{fontSize:10,color:K.teal,fontWeight:800}}>INVOICE</div><div style={{fontSize:19,fontWeight:900,color:K.teal,marginTop:3}}>{money(invoice.invoice_total)}</div></div>
        <div style={{padding:12,borderRadius:10,background:gp>=0?K.plumL:K.roseL}}><div style={{fontSize:10,color:gp>=0?K.plum:K.rose,fontWeight:800}}>GROSS PROFIT</div><div style={{fontSize:19,fontWeight:900,color:gp>=0?K.plum:K.rose,marginTop:3}}>{money(gp)}</div></div>
      </div>
      <div className="g2" style={{marginBottom:18}}>
        <div><div style={{fontSize:10,color:K.t3,fontWeight:800}}>ISSUED</div><div style={{fontSize:13,fontWeight:700,marginTop:2}}>{fmt(invoice.issued_at)}</div></div>
        <div><div style={{fontSize:10,color:K.t3,fontWeight:800}}>DUE</div><div style={{fontSize:13,fontWeight:700,marginTop:2,color:invoice.is_overdue?K.rose:K.text}}>{fmt(invoice.due_date)}</div></div>
        <div><div style={{fontSize:10,color:K.t3,fontWeight:800}}>PAID</div><div style={{fontSize:13,fontWeight:700,marginTop:2}}>{money(invoice.amount_paid)}</div></div>
        <div><div style={{fontSize:10,color:K.t3,fontWeight:800}}>BALANCE</div><div style={{fontSize:13,fontWeight:900,marginTop:2,color:num(invoice.balance_due)>0?K.rose:K.teal}}>{money(invoice.balance_due)}</div></div>
      </div>
      <div style={{fontWeight:800,fontSize:13,marginBottom:8}}>Products</div>
      <div style={{border:'1px solid '+K.border,borderRadius:11,overflow:'hidden',marginBottom:18}}>
        {lines.length?lines.map((it,i)=><div key={it.id} style={{padding:'10px 12px',borderBottom:i<lines.length-1?'1px solid '+K.border:'none'}}><div style={{display:'flex',justifyContent:'space-between',gap:10}}><strong style={{fontSize:12.5}}>{it.product_name}</strong><strong style={{fontSize:12.5}}>{money(it.revenue)}</strong></div><div style={{fontSize:11,color:K.t3,marginTop:3}}>{it.sku||'No SKU'} · {num(it.cases_sold)} case{num(it.cases_sold)===1?'':'s'} @ {money(it.sale_price)}</div></div>):<Empty>No invoice line items</Empty>}
      </div>
      {num(invoice.balance_due)>0&&<div style={{display:'flex',gap:8,flexWrap:'wrap',marginBottom:18}}><button className="btn btn-p btn-sm" onClick={()=>onPay(invoice)}>Record Payment</button><button className="btn btn-g btn-sm" onClick={()=>onFollow(invoice)}>Collection Follow-Up</button></div>}
      <div style={{fontWeight:800,fontSize:13,marginBottom:7}}>Payment History</div>
      {pays.length?pays.map(p=><div key={p.id} style={{display:'flex',justifyContent:'space-between',padding:'9px 0',borderBottom:'1px solid '+K.border,fontSize:12}}><div><strong>{fmt(p.payment_date)}</strong><div style={{color:K.t3,marginTop:2}}>{p.payment_method||'Payment'}{p.reference?' · '+p.reference:''}</div></div><strong style={{color:K.teal}}>{money(p.amount)}</strong></div>):<div style={{fontSize:12,color:K.t3,marginBottom:17}}>No payment ledger entries</div>}
      <div style={{fontWeight:800,fontSize:13,marginTop:18,marginBottom:7}}>Collections</div>
      {follows.length?follows.map(f=><div key={f.id} style={{padding:'9px 0',borderBottom:'1px solid '+K.border,fontSize:12}}><div style={{display:'flex',justifyContent:'space-between'}}><strong>{f.activity_type||'Follow-Up'}</strong><span style={{color:K.t3}}>{fmt(f.activity_date)}</span></div>{f.notes&&<div style={{color:K.t2,marginTop:3}}>{f.notes}</div>}{f.next_follow_up_date&&<div style={{color:K.amber,fontWeight:700,marginTop:3}}>Next: {fmt(f.next_follow_up_date)}</div>}</div>):<div style={{fontSize:12,color:K.t3}}>No collection activity</div>}
    </div>
  </div>
}

export default function SalesWorkspace({supabase,prospects,user,go}){
  const [view,setView]=useState(()=>{try{return sessionStorage.getItem('lagom_sales_view')||'overview'}catch{return 'overview'}});
  const [loading,setLoading]=useState(true);
  const [products,setProducts]=useState([]),[invoices,setInvoices]=useState([]),[items,setItems]=useState([]),[payments,setPayments]=useState([]),[collections,setCollections]=useState([]),[reorders,setReorders]=useState([]),[performance,setPerformance]=useState([]),[commissions,setCommissions]=useState([]);
  const [selected,setSelected]=useState(null),[search,setSearch]=useState(''),[status,setStatus]=useState('All'),[rep,setRep]=useState('All'),[message,setMessage]=useState('');
  const [showNew,setShowNew]=useState(false),[payFor,setPayFor]=useState(null),[followFor,setFollowFor]=useState(null),[saving,setSaving]=useState(false);
  const me=(user?.display_name||user?.name||'').trim(),isAdmin=user?.role==='admin';

  const load=useCallback(async()=>{
    setLoading(true);
    const q=await Promise.all([
      supabase.from('products').select('*').eq('status','Active').order('product_line').order('name'),
      supabase.from('crm_invoice_rollup').select('*').order('issued_at',{ascending:false}),
      supabase.from('invoice_items').select('*').order('created_at'),
      supabase.from('payments').select('*').order('payment_date',{ascending:false}),
      supabase.from('collection_activities').select('*').order('activity_date',{ascending:false}),
      supabase.from('crm_reorder_opportunities').select('*').order('days_since_last_order',{ascending:false}),
      supabase.from('crm_product_performance').select('*').order('revenue',{ascending:false}),
      supabase.from('crm_commission_eligible').select('*').order('commission_eligible_date',{ascending:false})
    ]);
    setProducts(q[0].data||[]);setInvoices(q[1].data||[]);setItems(q[2].data||[]);setPayments(q[3].data||[]);setCollections(q[4].data||[]);setReorders(q[5].data||[]);setPerformance(q[6].data||[]);setCommissions(q[7].data||[]);setLoading(false);
  },[supabase]);
  useEffect(()=>{load();try{sessionStorage.removeItem('lagom_sales_view')}catch{}},[load]);

  const scoped=useMemo(()=>isAdmin?invoices:invoices.filter(i=>(i.rep_name||'').toLowerCase()===me.toLowerCase()),[invoices,isAdmin,me]);
  const scopedPerformance=useMemo(()=>{
    if(isAdmin)return performance;
    const invoiceMap=new Map(scoped.filter(i=>i.status!=='Draft').map(i=>[i.id,i]));
    const map={};
    items.forEach(it=>{
      const inv=invoiceMap.get(it.invoice_id);if(!inv)return;
      const key=it.product_id||it.sku||it.product_name;
      if(!map[key])map[key]={product_id:it.product_id,sku:it.sku,product_name:it.product_name,category:it.category,cases_sold:0,revenue:0,total_cogs:0,gross_profit:0,activeSet:new Set(),invoiceSet:new Set(),last_sale_date:null};
      const r=map[key];r.cases_sold+=num(it.cases_sold);r.revenue+=num(it.revenue);r.total_cogs+=num(it.total_cogs);r.gross_profit+=num(it.gross_profit);if(inv.prospect_id)r.activeSet.add(inv.prospect_id);r.invoiceSet.add(inv.id);if(!r.last_sale_date||inv.issued_at>r.last_sale_date)r.last_sale_date=inv.issued_at;
    });
    return Object.values(map).map(r=>({...r,active_accounts:r.activeSet.size,invoice_count:r.invoiceSet.size})).sort((a,b)=>b.revenue-a.revenue);
  },[isAdmin,performance,scoped,items]);
  const scopedReorders=useMemo(()=>isAdmin?reorders:reorders.filter(i=>(i.rep_name||'').toLowerCase()===me.toLowerCase()),[reorders,isAdmin,me]);
  const scopedCommissions=useMemo(()=>isAdmin?commissions:commissions.filter(i=>(i.rep_name||'').toLowerCase()===me.toLowerCase()),[commissions,isAdmin,me]);
  const reps=useMemo(()=>[...new Set(invoices.map(i=>i.rep_name).filter(Boolean))].sort(),[invoices]);
  const filtered=useMemo(()=>scoped.filter(i=>{const q=search.toLowerCase().trim(),state=invState(i);return(!q||(String(i.invoice_number)+' '+String(i.account_name)+' '+String(i.rep_name||'')).toLowerCase().includes(q))&&(status==='All'||state===status)&&(rep==='All'||i.rep_name===rep)}),[scoped,search,status,rep]);

  const monthStart=useMemo(()=>{const d=new Date();d.setDate(1);return d.toISOString().slice(0,10)},[]);
  const monthInvoices=scoped.filter(i=>i.issued_at>=monthStart&&i.status!=='Draft'),monthIds=new Set(monthInvoices.map(i=>i.id)),monthItems=items.filter(i=>monthIds.has(i.invoice_id));
  const monthCases=monthItems.reduce((s,i)=>s+num(i.cases_sold),0),monthSales=monthInvoices.reduce((s,i)=>s+num(i.invoice_total),0),monthGP=monthItems.reduce((s,i)=>s+num(i.gross_profit),0);
  const doors=new Set(monthInvoices.map(i=>i.prospect_id||i.account_name)).size,outstanding=scoped.reduce((s,i)=>s+num(i.balance_due),0),overdue=scoped.filter(i=>i.is_overdue).reduce((s,i)=>s+num(i.balance_due),0);
  const paidMonth=scoped.filter(i=>i.payment_date>=monthStart).reduce((s,i)=>s+num(i.amount_paid),0),dueReorders=scopedReorders.filter(i=>['Due Soon','Due','Overdue'].includes(i.reorder_status)),commissionEarned=scopedCommissions.reduce((s,i)=>s+num(i.commission_amount),0);

  const tabs=[['overview','Overview'],['transactions','Transactions'],['reorders','Reorders'],['ar','AR'],['products','Products']];
  const header=<><div className="tab-h" style={{marginBottom:14}}><div><div className="section-label" style={{marginBottom:7}}>Commercial operations</div><h2>Sales & Depletion</h2><div style={{fontSize:12,color:K.t3,marginTop:6,maxWidth:620,lineHeight:1.45}}>Monitor sell-in, account velocity, receivables, product performance, and the next revenue actions from one workspace.</div></div><button className="btn btn-p" onClick={()=>setShowNew(true)}>+ New Invoice</button></div><div style={{display:'inline-flex',padding:4,border:'1px solid '+K.border,borderRadius:12,background:'#F6F7F5',gap:3,maxWidth:'100%',overflowX:'auto'}}>{tabs.map(([id,label])=><button key={id} onClick={()=>setView(id)} style={{border:'none',borderRadius:9,padding:'8px 12px',fontSize:11.5,fontWeight:750,whiteSpace:'nowrap',background:view===id?'#fff':'transparent',color:view===id?K.text:K.t2,boxShadow:view===id?'0 1px 4px rgba(23,32,28,.08)':'none'}}>{label}</button>)}</div>{message&&<div style={{marginTop:12,padding:'11px 13px',borderRadius:10,background:K.tealL,color:K.teal,fontSize:12.5,fontWeight:700,border:'1px solid #D7E8DF'}}>{message}</div>}</>;
  const overview=<><div className="g4" style={{marginTop:18,marginBottom:18}}><Stat label="Cases Sold MTD" value={monthCases} sub={doors+' active doors'}/><Stat label="Net Sales MTD" value={shortMoney(monthSales)} sub={monthInvoices.length+' invoices'} color={K.plum}/><Stat label="Gross Profit MTD" value={shortMoney(monthGP)} sub={monthSales?((monthGP/monthSales)*100).toFixed(1)+'% margin':'No sales this month'} color={K.amber}/><Stat label="Outstanding AR" value={shortMoney(outstanding)} sub={overdue?shortMoney(overdue)+' overdue':'No overdue balance'} color={overdue?K.rose:K.teal}/></div><div className="g2"><div className="card"><div style={{fontWeight:850,fontSize:14,marginBottom:12}}>Reorder Opportunities</div>{dueReorders.length?dueReorders.slice(0,6).map((r,i)=><div key={r.prospect_id} style={{display:'flex',gap:9,alignItems:'center',padding:'9px 0',borderTop:i?'1px solid '+K.border:'none'}}><div style={{width:8,height:8,borderRadius:'50%',background:reorderColor(r.reorder_status)}}/><div style={{flex:1,minWidth:0}}><strong style={{fontSize:12.5}}>{r.account_name}</strong><div style={{fontSize:11,color:K.t3}}>{r.days_since_last_order} days since order{r.avg_reorder_days?' · '+r.avg_reorder_days+' day cadence':''}</div></div><Badge label={r.reorder_status} color={reorderColor(r.reorder_status)}/></div>):<Empty>Reorder cadence is learning from transaction history.</Empty>}</div><div className="card"><div style={{fontWeight:850,fontSize:14,marginBottom:12}}>Commercial Snapshot</div>{[['Paid this month',money(paidMonth),K.teal],['Overdue AR',money(overdue),overdue?K.rose:K.teal],['Commission eligible',money(commissionEarned),K.plum],['Reorders due',String(dueReorders.filter(x=>['Due','Overdue'].includes(x.reorder_status)).length),K.amber]].map(([l,v,c],i)=><div key={l} style={{display:'flex',justifyContent:'space-between',padding:'11px 0',borderTop:i?'1px solid '+K.border:'none'}}><span style={{fontSize:12.5,color:K.t2}}>{l}</span><strong style={{color:c}}>{v}</strong></div>)}</div></div></>;

  const transactions=<><div style={{display:'flex',gap:8,margin:'18px 0 12px',flexWrap:'wrap'}}><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search account or invoice..." style={{maxWidth:250}}/><select value={status} onChange={e=>setStatus(e.target.value)} style={{width:145}}>{['All','Unpaid','Partial','Paid','Overdue','Draft'].map(x=><option key={x}>{x}</option>)}</select>{isAdmin&&<select value={rep} onChange={e=>setRep(e.target.value)} style={{width:145}}><option>All</option>{reps.map(x=><option key={x}>{x}</option>)}</select>}</div><div className="ovfl"><table><thead><tr><th>Invoice</th><th>Account</th><th>Rep</th><th>Cases</th><th>Revenue</th><th>Status</th><th className="hide-mob">Issued</th><th>Balance</th></tr></thead><tbody>{filtered.length?filtered.map(i=>{const cases=items.filter(x=>x.invoice_id===i.id).reduce((s,x)=>s+num(x.cases_sold),0),state=invState(i);return <tr key={i.id} onClick={()=>setSelected(i)} style={{cursor:'pointer'}}><td style={{fontFamily:'monospace',fontWeight:800,color:K.teal}}>{i.invoice_number}</td><td><strong style={{fontSize:12.5}}>{i.account_name}</strong><div style={{fontSize:10.5,color:K.t3}}>{i.city||''}{i.county?' · '+i.county+' County':''}</div></td><td style={{fontSize:12,color:K.t2}}>{i.rep_name||'-'}</td><td style={{fontWeight:800}}>{cases}</td><td style={{fontWeight:800}}>{money(i.invoice_total)}</td><td><Badge label={state} color={statusColor(state)}/></td><td className="hide-mob" style={{fontSize:12}}>{fmt(i.issued_at)}</td><td style={{fontWeight:900,color:num(i.balance_due)>0?K.rose:K.teal}}>{money(i.balance_due)}</td></tr>}):<tr><td colSpan={8}><Empty>No transactions match these filters.</Empty></td></tr>}</tbody></table></div></>;

  const reorderView=<><div className="g3" style={{marginTop:18,marginBottom:16}}><Stat label="Overdue" value={scopedReorders.filter(x=>x.reorder_status==='Overdue').length} sub="Past learned cadence" color={K.rose}/><Stat label="Due" value={scopedReorders.filter(x=>x.reorder_status==='Due').length} sub="At normal reorder interval" color={K.amber}/><Stat label="Due Soon" value={scopedReorders.filter(x=>x.reorder_status==='Due Soon').length} sub="Approaching cadence" color={K.plum}/></div><div style={{display:'flex',justifyContent:'flex-end',marginBottom:10}}><button className="btn btn-g btn-sm" onClick={()=>go&&go('routes')}>Open Route Builder</button></div><div className="ovfl"><table><thead><tr><th>Account</th><th>Status</th><th>Last Order</th><th>Days Since</th><th>Avg Cadence</th><th>Typical Order</th></tr></thead><tbody>{scopedReorders.length?scopedReorders.map(r=><tr key={r.prospect_id}><td><strong>{r.account_name}</strong><div style={{fontSize:10.5,color:K.t3}}>{r.city||''}</div></td><td><Badge label={r.reorder_status} color={reorderColor(r.reorder_status)}/></td><td>{fmt(r.last_order_date)}</td><td style={{fontWeight:800}}>{r.days_since_last_order}</td><td>{r.avg_reorder_days?r.avg_reorder_days+' days':'Learning'}</td><td style={{fontWeight:700}}>{money(r.avg_order_value)}</td></tr>):<tr><td colSpan={6}><Empty>No reorder history yet.</Empty></td></tr>}</tbody></table></div></>;

  const openAR=scoped.filter(i=>num(i.balance_due)>0),buckets=['Current','1-30','31-60','61-90','90+'];
  const ar=<><div className="g4" style={{marginTop:18,marginBottom:16}}><Stat label="Outstanding" value={shortMoney(outstanding)} sub={openAR.length+' open invoices'} color={K.plum}/><Stat label="Overdue" value={shortMoney(overdue)} sub={scoped.filter(i=>i.is_overdue).length+' overdue invoices'} color={overdue?K.rose:K.teal}/><Stat label="Paid MTD" value={shortMoney(paidMonth)} sub="Cash recorded this month"/><Stat label="Follow-Ups Due" value={openAR.filter(i=>i.next_follow_up_date&&i.next_follow_up_date<=today()).length} sub="Collections requiring action" color={K.amber}/></div><div className="card" style={{marginBottom:16}}><div style={{fontWeight:850,fontSize:14,marginBottom:11}}>AR Aging</div><div style={{display:'grid',gridTemplateColumns:'repeat(5,minmax(105px,1fr))',gap:8,overflowX:'auto'}}>{buckets.map(b=><div key={b} style={{padding:11,border:'1px solid '+K.border,borderRadius:9,minWidth:105}}><div style={{fontSize:10,color:K.t3,fontWeight:800}}>{b}</div><div style={{fontSize:16,fontWeight:900,color:b==='Current'?K.teal:b==='90+'?K.rose:K.amber,marginTop:4}}>{money(openAR.filter(i=>i.aging_bucket===b).reduce((s,i)=>s+num(i.balance_due),0))}</div></div>)}</div></div><div className="ovfl"><table><thead><tr><th>Invoice</th><th>Account</th><th>Balance</th><th>Due</th><th>Age</th><th>Next Follow-Up</th><th>Action</th></tr></thead><tbody>{openAR.length?openAR.map(i=><tr key={i.id}><td onClick={()=>setSelected(i)} style={{fontFamily:'monospace',fontWeight:800,color:K.teal,cursor:'pointer'}}>{i.invoice_number}</td><td style={{fontWeight:700}}>{i.account_name}</td><td style={{fontWeight:900,color:i.is_overdue?K.rose:K.text}}>{money(i.balance_due)}</td><td style={{color:i.is_overdue?K.rose:K.t2}}>{fmt(i.due_date)}</td><td><Badge label={i.aging_bucket} color={i.is_overdue?K.rose:K.teal}/></td><td>{fmt(i.next_follow_up_date)}</td><td><div style={{display:'flex',gap:5}}><button className="btn btn-p btn-sm" onClick={()=>setPayFor(i)}>Pay</button><button className="btn btn-g btn-sm" onClick={()=>setFollowFor(i)}>Follow-Up</button></div></td></tr>):<tr><td colSpan={7}><Empty>No outstanding AR.</Empty></td></tr>}</tbody></table></div></>;

  const productView=<><div className="g4" style={{marginTop:18,marginBottom:16}}><Stat label="Catalog SKUs" value={products.length} sub="Active products"/><Stat label="Cases Sold" value={scopedPerformance.reduce((s,x)=>s+num(x.cases_sold),0)} sub="Recorded invoice lines" color={K.plum}/><Stat label="Sales" value={shortMoney(scopedPerformance.reduce((s,x)=>s+num(x.revenue),0))} sub="All recorded invoices" color={K.amber}/><Stat label="Gross Profit" value={shortMoney(scopedPerformance.reduce((s,x)=>s+num(x.gross_profit),0))} sub="Captured COGS basis"/></div><div className="ovfl"><table><thead><tr><th>Product</th><th>SKU</th><th>Cases</th><th>Revenue</th><th>Gross Profit</th><th>Accounts</th><th>Last Sale</th></tr></thead><tbody>{scopedPerformance.length?scopedPerformance.map(p=><tr key={p.product_id||p.sku||p.product_name}><td><strong>{p.product_name}</strong><div style={{fontSize:10.5,color:K.t3}}>{p.product_line||p.category||''}</div></td><td style={{fontFamily:'monospace',fontSize:11.5}}>{p.sku||'-'}</td><td style={{fontWeight:850}}>{num(p.cases_sold)}</td><td style={{fontWeight:850,color:K.teal}}>{money(p.revenue)}</td><td style={{fontWeight:750,color:num(p.gross_profit)>=0?K.plum:K.rose}}>{money(p.gross_profit)}</td><td>{p.active_accounts||0}</td><td>{fmt(p.last_sale_date)}</td></tr>):<tr><td colSpan={7}><Empty>No product performance data yet.</Empty></td></tr>}</tbody></table></div></>;

  const [form,setForm]=useState({prospect_id:'',issued_at:today(),due_date:plusDays(today(),30),sale_type:'',rep_name:me,notes:'',amount_paid:0,payment_method:''});
  const [lines,setLines]=useState([{product_id:'',cases:1,price:''}]);
  const account=prospects.find(p=>p.id===form.prospect_id),prior=scoped.filter(i=>i.prospect_id===form.prospect_id&&i.status!=='Draft').length,saleType=form.sale_type||(prior?'Reorder':'New Placement');
  const hydrated=lines.map(l=>{const p=products.find(x=>x.id===l.product_id),price=l.price===''?num(p?.retail_price):num(l.price),cases=Math.max(0,num(l.cases)),hasCogs=p?.cogs_per_case!==null&&p?.cogs_per_case!==undefined,cogs=hasCogs?num(p.cogs_per_case):null;return {...l,p,price,cases,revenue:cases*price,cogs,total_cogs:cogs===null?null:cases*cogs,gp:cogs===null?null:cases*price-cases*cogs}});
  const total=hydrated.reduce((s,l)=>s+l.revenue,0);

  const createInvoice=async()=>{
    if(!account||!hydrated.some(l=>l.p&&l.cases>0))return;setSaving(true);
    try{
      const nr=await supabase.rpc('next_invoice_number');if(nr.error)throw nr.error;
      const repName=form.rep_name||account.assigned_to||me||null;
      const o=await supabase.from('orders').insert({prospect_id:account.id,account_name:account.business_name,status:'Confirmed',total_amount:total,notes:form.notes||null,created_by:repName}).select().single();if(o.error)throw o.error;
      const valid=hydrated.filter(l=>l.p&&l.cases>0);
      const oi=await supabase.from('order_items').insert(valid.map(l=>({order_id:o.data.id,product_id:l.p.id,product_name:l.p.name,quantity:l.cases,unit_price:l.price,total_price:l.revenue})));if(oi.error)throw oi.error;
      for(const line of valid){
        if(line.p.quantity===null||line.p.quantity===undefined)continue;
        const before=num(line.p.quantity),after=Math.max(0,before-line.cases);
        await supabase.from('products').update({quantity:after,updated_at:new Date().toISOString()}).eq('id',line.p.id);
        await supabase.from('inventory_movements').insert({product_id:line.p.id,movement_type:'Order',quantity_change:-line.cases,quantity_before:before,quantity_after:after,order_id:o.data.id,notes:'Sales invoice '+String(nr.data),created_by:me});
      }
      const paid=Math.min(num(form.amount_paid),total);
      const iv=await supabase.from('invoices').insert({order_id:o.data.id,prospect_id:account.id,account_name:account.business_name,rep_name:repName,invoice_number:nr.data,sale_type:saleType,status:paid>=total&&total>0?'Paid':paid>0?'Partial':'Unpaid',issued_at:form.issued_at,due_date:form.due_date,subtotal:total,invoice_total:total,amount_due:total,amount_paid:0,balance_due:total,collection_status:paid>=total&&total>0?'Closed':'Open',notes:form.notes||null,source:'crm'}).select().single();if(iv.error)throw iv.error;
      const ii=await supabase.from('invoice_items').insert(valid.map(l=>({invoice_id:iv.data.id,product_id:l.p.id,sku:l.p.sku||null,product_name:l.p.name,description:l.p.description||null,category:l.p.depletion_category||l.p.category||null,cases_sold:l.cases,sale_price:l.price,revenue:l.revenue,cogs_per_case:l.cogs,total_cogs:l.total_cogs,gross_profit:l.gp,cost_reference:l.p.cost_per_unit_reference??null})));if(ii.error)throw ii.error;
      if(paid>0){const pp=await supabase.from('payments').insert({invoice_id:iv.data.id,prospect_id:account.id,amount:paid,payment_date:form.issued_at,payment_method:form.payment_method||null,reference:'Initial payment',created_by:me,source:'crm'});if(pp.error)throw pp.error}
      setShowNew(false);setForm({prospect_id:'',issued_at:today(),due_date:plusDays(today(),30),sale_type:'',rep_name:me,notes:'',amount_paid:0,payment_method:''});setLines([{product_id:'',cases:1,price:''}]);setMessage('Invoice '+nr.data+' created and linked to the account and order workflow.');await load()
    }catch(e){alert('Could not create invoice: '+(e?.message||e))}finally{setSaving(false)}
  };

  const [pay,setPay]=useState({amount:'',payment_date:today(),payment_method:'',reference:'',notes:''});
  const savePay=async()=>{if(!payFor||num(pay.amount)<=0)return;setSaving(true);const e=await supabase.from('payments').insert({invoice_id:payFor.id,prospect_id:payFor.prospect_id,amount:Math.min(num(pay.amount),num(payFor.balance_due)),payment_date:pay.payment_date,payment_method:pay.payment_method||null,reference:pay.reference||null,notes:pay.notes||null,created_by:me,source:'crm'});if(e.error)alert(e.error.message);else{setPayFor(null);setPay({amount:'',payment_date:today(),payment_method:'',reference:'',notes:''});setMessage('Payment recorded and AR reconciled.');await load()}setSaving(false)};
  const [follow,setFollow]=useState({activity_type:'Call',activity_date:today(),notes:'',next_follow_up_date:plusDays(today(),7)});
  const saveFollow=async()=>{if(!followFor)return;setSaving(true);const a=await supabase.from('collection_activities').insert({invoice_id:followFor.id,prospect_id:followFor.prospect_id,rep_name:me,activity_date:follow.activity_date,activity_type:follow.activity_type,notes:follow.notes||null,next_follow_up_date:follow.next_follow_up_date||null});if(!a.error){await supabase.from('invoices').update({collection_status:'Follow-Up',last_follow_up_date:follow.activity_date,next_follow_up_date:follow.next_follow_up_date||null}).eq('id',followFor.id);if(follow.next_follow_up_date)await supabase.from('crm_tasks').insert({prospect_id:followFor.prospect_id,invoice_id:followFor.id,task_type:'AR Follow-Up',title:'Collect '+money(followFor.balance_due)+' from '+followFor.account_name,assigned_to:me,due_date:follow.next_follow_up_date,priority:'High',status:'Open'});setFollowFor(null);setFollow({activity_type:'Call',activity_date:today(),notes:'',next_follow_up_date:plusDays(today(),7)});await load()}else alert(a.error.message);setSaving(false)};

  if(loading)return <div className="fade">{header}<div style={{padding:60,textAlign:'center',color:K.t3}}>Loading sales operations data...</div></div>;

  return <div className="fade">{header}{view==='overview'&&overview}{view==='transactions'&&transactions}{view==='reorders'&&reorderView}{view==='ar'&&ar}{view==='products'&&productView}
    <InvoicePanel invoice={selected} items={items} payments={payments} collections={collections} onClose={()=>setSelected(null)} onPay={setPayFor} onFollow={setFollowFor}/>
    {showNew&&<div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&setShowNew(false)}><div className="modal modal-wide" style={{maxWidth:780}}><div style={{display:'flex',justifyContent:'space-between',marginBottom:16}}><div><div style={{fontSize:18,fontWeight:900}}>New Invoice</div><div style={{fontSize:12,color:K.t3,marginTop:3}}>Creates the backing order, invoice, product lines, and optional payment.</div></div><button onClick={()=>setShowNew(false)} style={{border:'none',background:'transparent',fontSize:24,color:K.t3}}>×</button></div>
      <div className="frow" style={{marginBottom:12}}><Field label="Account *"><select value={form.prospect_id} onChange={e=>setForm(f=>({...f,prospect_id:e.target.value,sale_type:''}))}><option value="">Select account...</option>{prospects.slice().sort((a,b)=>(a.business_name||'').localeCompare(b.business_name||'')).map(p=><option key={p.id} value={p.id}>{p.business_name}{p.city?' · '+p.city:''}</option>)}</select></Field><Field label="Sales Rep"><input value={form.rep_name} onChange={e=>setForm(f=>({...f,rep_name:e.target.value}))} placeholder={account?.assigned_to||'Rep name'}/></Field></div>
      <div className="frow" style={{marginBottom:12}}><Field label="Invoice Date"><input type="date" value={form.issued_at} onChange={e=>setForm(f=>({...f,issued_at:e.target.value}))}/></Field><Field label="Due Date"><input type="date" value={form.due_date} onChange={e=>setForm(f=>({...f,due_date:e.target.value}))}/></Field></div>
      <Field label="Sale Type"><select value={form.sale_type} onChange={e=>setForm(f=>({...f,sale_type:e.target.value}))} style={{maxWidth:230}}><option value="">Auto: {prior?'Reorder':'New Placement'}</option><option>New Placement</option><option>Reorder</option></select></Field>
      <div style={{fontWeight:850,fontSize:13,marginTop:15,marginBottom:8}}>Products</div>{lines.map((l,i)=>{const h=hydrated[i];return <div key={i} className="sales-invoice-line"><select value={l.product_id} onChange={e=>setLines(v=>v.map((x,j)=>j===i?{...x,product_id:e.target.value,price:''}:x))}><option value="">Select product...</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}{p.sku?' · '+p.sku:''}</option>)}</select><input className="sales-line-qty" aria-label="Cases" type="number" min="0" value={l.cases} onChange={e=>setLines(v=>v.map((x,j)=>j===i?{...x,cases:e.target.value}:x))}/><input className="sales-line-price" aria-label="Price per case" type="number" min="0" step=".01" value={l.price===''?(h?.price||''):l.price} onChange={e=>setLines(v=>v.map((x,j)=>j===i?{...x,price:e.target.value}:x))}/><strong className="sales-line-total">{money(h?.revenue)}</strong><button className="sales-line-remove" aria-label="Remove product" onClick={()=>setLines(v=>v.length===1?v:v.filter((_,j)=>j!==i))} style={{border:'none',background:'transparent',fontSize:19,color:K.t3}}>×</button></div>})}<button className="btn btn-g btn-sm" onClick={()=>setLines(v=>[...v,{product_id:'',cases:1,price:''}])}>+ Add Product</button>
      <div className="frow" style={{marginTop:14}}><Field label="Amount Paid Now"><input type="number" min="0" step=".01" value={form.amount_paid} onChange={e=>setForm(f=>({...f,amount_paid:e.target.value}))}/></Field><Field label="Payment Method"><select value={form.payment_method} onChange={e=>setForm(f=>({...f,payment_method:e.target.value}))}><option value="">Not specified</option><option>ACH</option><option>Check</option><option>Cash</option><option>Card</option><option>Other</option></select></Field></div><div style={{marginTop:12}}><Field label="Notes"><textarea rows="2" value={form.notes} onChange={e=>setForm(f=>({...f,notes:e.target.value}))}/></Field></div>
      <div style={{marginTop:16,padding:14,borderRadius:11,background:K.slateL,display:'flex',justifyContent:'space-between',alignItems:'center',gap:10}}><div><div style={{fontSize:10,color:K.t3,fontWeight:800}}>TOTAL</div><div style={{fontSize:23,fontWeight:900,color:K.teal}}>{money(total)}</div></div><div style={{display:'flex',gap:8}}><button className="btn btn-g" onClick={()=>setShowNew(false)}>Cancel</button><button className="btn btn-p" disabled={saving||!account||total<=0} onClick={createInvoice}>{saving?'Saving...':'Create Invoice'}</button></div></div>
    </div></div>}
    {payFor&&<div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&setPayFor(null)}><div className="modal"><h3 style={{fontSize:18,marginBottom:4}}>Record Payment</h3><div style={{fontSize:12,color:K.t3,marginBottom:14}}>{payFor.invoice_number} · {payFor.account_name} · {money(payFor.balance_due)} remaining</div><div className="frow" style={{marginBottom:12}}><Field label="Amount *"><input type="number" min=".01" max={payFor.balance_due} step=".01" value={pay.amount} onChange={e=>setPay(x=>({...x,amount:e.target.value}))}/></Field><Field label="Payment Date"><input type="date" value={pay.payment_date} onChange={e=>setPay(x=>({...x,payment_date:e.target.value}))}/></Field></div><div className="frow"><Field label="Method"><select value={pay.payment_method} onChange={e=>setPay(x=>({...x,payment_method:e.target.value}))}><option value="">Select...</option><option>ACH</option><option>Check</option><option>Cash</option><option>Card</option><option>Other</option></select></Field><Field label="Reference"><input value={pay.reference} onChange={e=>setPay(x=>({...x,reference:e.target.value}))}/></Field></div><div style={{display:'flex',gap:8,marginTop:15}}><button className="btn btn-p" disabled={saving||num(pay.amount)<=0} onClick={savePay}>Record Payment</button><button className="btn btn-g" onClick={()=>setPayFor(null)}>Cancel</button></div></div></div>}
    {followFor&&<div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&setFollowFor(null)}><div className="modal"><h3 style={{fontSize:18,marginBottom:4}}>Collection Follow-Up</h3><div style={{fontSize:12,color:K.t3,marginBottom:14}}>{followFor.invoice_number} · {followFor.account_name}</div><div className="frow" style={{marginBottom:12}}><Field label="Type"><select value={follow.activity_type} onChange={e=>setFollow(x=>({...x,activity_type:e.target.value}))}><option>Call</option><option>Email</option><option>In-Person</option><option>Text</option><option>Other</option></select></Field><Field label="Activity Date"><input type="date" value={follow.activity_date} onChange={e=>setFollow(x=>({...x,activity_date:e.target.value}))}/></Field></div><Field label="Notes"><textarea rows="3" value={follow.notes} onChange={e=>setFollow(x=>({...x,notes:e.target.value}))}/></Field><div style={{marginTop:12}}><Field label="Next Follow-Up"><input type="date" value={follow.next_follow_up_date} onChange={e=>setFollow(x=>({...x,next_follow_up_date:e.target.value}))}/></Field></div><div style={{display:'flex',gap:8,marginTop:15}}><button className="btn btn-p" disabled={saving} onClick={saveFollow}>Save Follow-Up</button><button className="btn btn-g" onClick={()=>setFollowFor(null)}>Cancel</button></div></div></div>}
  </div>
}
