import React from 'react'
import {Link,NavLink,useLocation,useNavigate} from 'react-router-dom'
import {Bell,ChevronLeft,ChevronRight,CircleHelp,Gift,LockKeyhole,Mail,MapPin,PackageCheck,Search,Settings,ShieldCheck,ShoppingBag,User,Truck,RotateCcw,FileText,MessageCircle} from 'lucide-react'
import {m,Stagger,StaggerItem,motionTokens} from './motionSystem'
import './styles/account.css'

const CART_KEY='lagom-beverage-cart-v1'
const navItems=[
  [PackageCheck,'My Orders','Review purchases and order status','orders'],
  [Gift,'Rewards','Shop. Earn. Get more.','rewards','reward'],
  [Settings,'Account Settings','Profile and account details','settings'],
  [Bell,'Notifications','Choose the updates you receive','notifications'],
  [CircleHelp,'Help & Support','Answers and customer support','support'],
]
const notifications=[['Order updates','Status updates about your orders.',true],['Rewards & offers','News about rewards and offers.',true],['Product updates','New products and brand news.',false],['Account security','Important account alerts.',true]]

function cartCount(){try{return(JSON.parse(localStorage.getItem(CART_KEY)||'[]')||[]).reduce((sum,item)=>sum+(Number(item.qty)||0),0)}catch{return 0}}
function AccountHeader(){const[count,setCount]=React.useState(cartCount);React.useEffect(()=>{const sync=()=>setCount(cartCount());window.addEventListener('storage',sync);window.addEventListener('lagom-cart-change',sync);return()=>{window.removeEventListener('storage',sync);window.removeEventListener('lagom-cart-change',sync)}},[]);return <><div className="announcement account-announcement">HEMP-DERIVED THC · FOR ADULTS 21+ · ENJOY RESPONSIBLY</div><header className="account-site-header"><nav className="account-site-nav" aria-label="Primary navigation"><div className="account-site-nav__group"><NavLink to="/shop">Shop</NavLink><NavLink to="/merch">Merch</NavLink></div><Link className="account-site-brand" to="/"><img src="/lagom-logo.svg" alt="Lagom Naturals"/></Link><div className="account-site-nav__group"><NavLink to="/visit">Find Us</NavLink><NavLink to="/about">Our Story</NavLink></div></nav><div className="account-site-tools"><Link to="/shop" aria-label="Search"><Search/></Link><Link to="/account" aria-current="page" aria-label="Account"><User/></Link><Link className="account-cart-icon" to="/cart" aria-label={`Cart, ${count} items`}><ShoppingBag/>{count>0&&<b>{count}</b>}</Link></div></header></>}
function HubRow({Icon,label,detail,section,reward=false,onOpen}){return <StaggerItem><m.button type="button" className={`account-hub-row${reward?' account-hub-row--reward':''}`} whileHover={{x:3}} whileTap={motionTokens.tap} onClick={()=>onOpen(section)}><span className="account-hub-row__icon"><Icon/></span><span className="account-hub-row__copy"><b>{label}</b><small>{detail}</small></span><ChevronRight className="account-hub-row__chevron"/></m.button></StaggerItem>}
function PageHead({title,description,onBack}){return <div className="account-page-head"><button type="button" onClick={onBack} aria-label="Back to account"><ChevronLeft/></button><div><h1>{title}</h1><p>{description}</p></div></div>}
function EmptyOrders(){return <section className="account-empty"><PackageCheck/><h2>No orders yet</h2><p>Your completed purchases will appear here when customer accounts and order history are connected.</p><Link to="/shop">Shop Lagom</Link></section>}
function Orders({onBack}){return <><PageHead title="My Orders" description="Track and review your Lagom purchases." onBack={onBack}/><EmptyOrders/></>}
function Rewards({onBack}){return <><PageHead title="Rewards" description="Shop. Earn. Get more." onBack={onBack}/><section className="account-reward-summary"><span><Gift/><small>Rewards balance</small><strong>—</strong></span><p>Your points and rewards activity will appear after the rewards service is connected.</p></section><div className="account-section-list"><div><ShoppingBag/><span><b>Make a purchase</b><small>Earn rewards through eligible purchases.</small></span></div><div><Gift/><span><b>Rewards activity</b><small>View earned and redeemed rewards.</small></span></div></div></>}
function SettingsPage({onBack}){return <><PageHead title="Account Settings" description="Manage your account information and preferences." onBack={onBack}/><div className="account-section-list"><div><User/><span><b>Profile information</b><small>Customer profile will appear when accounts are connected.</small></span><ChevronRight/></div><div><Mail/><span><b>Email</b><small>Manage the email associated with your account.</small></span><ChevronRight/></div><div><LockKeyhole/><span><b>Password & security</b><small>Manage sign-in and account security.</small></span><ChevronRight/></div><div><MapPin/><span><b>Addresses</b><small>Manage saved fulfillment addresses.</small></span><ChevronRight/></div></div></>}
function Notifications({onBack}){const[state,setState]=React.useState(()=>Object.fromEntries(notifications.map(([label,,enabled])=>[label,enabled])));return <><PageHead title="Notifications" description="Choose which Lagom updates you want to receive." onBack={onBack}/><div className="account-section-list account-notifications">{notifications.map(([label,detail])=><label key={label}><Bell/><span><b>{label}</b><small>{detail}</small></span><input type="checkbox" checked={state[label]} onChange={e=>setState(s=>({...s,[label]:e.target.checked}))}/><i aria-hidden="true"/></label>)}</div><p className="account-service-note">Preferences are shown as interface settings only until the customer messaging service is connected.</p></>}
function Support({onBack}){return <><PageHead title="Help & Support" description="Clear paths to answers and customer care." onBack={onBack}/><div className="account-section-list"><Link to="/learn"><MessageCircle/><span><b>FAQs</b><small>Common product and responsible-use questions.</small></span><ChevronRight/></Link><Link to="/visit"><Mail/><span><b>Contact us</b><small>Get in touch with the Lagom team.</small></span><ChevronRight/></Link><div><Truck/><span><b>Fulfillment</b><small>Order fulfillment information will be available with commerce services.</small></span></div><div><RotateCcw/><span><b>Returns & refunds</b><small>Policy information will appear when commerce policies are connected.</small></span></div><div><FileText/><span><b>Terms & policies</b><small>Review published brand and commerce policies.</small></span></div></div></>}
function Hub({onOpen}){return <><section className="account-hub__intro"><div className="account-hub__mark"><img src="/lagom-logo-icon.svg" alt="" aria-hidden="true"/></div><div><p>Welcome to</p><h1>Lagom</h1><span>Your place for orders, rewards and account preferences.</span></div></section><Stagger className="account-hub__rows">{navItems.map(([Icon,label,detail,section,type])=><HubRow key={label} Icon={Icon} label={label} detail={detail} section={section} reward={type==='reward'} onOpen={onOpen}/>)}</Stagger><p className="account-hub__backend-note">Customer-specific order, rewards and profile data will activate when the customer account and commerce backend is connected.</p></>}
export default function AccountPage(){const location=useLocation(),navigate=useNavigate();const section=new URLSearchParams(location.search).get('view')||'hub';const open=next=>navigate(`/account?view=${next}`);const back=()=>navigate('/account');let content=<Hub onOpen={open}/>;if(section==='orders')content=<Orders onBack={back}/>;if(section==='rewards')content=<Rewards onBack={back}/>;if(section==='settings')content=<SettingsPage onBack={back}/>;if(section==='notifications')content=<Notifications onBack={back}/>;if(section==='support')content=<Support onBack={back}/>;return <div className="account-route"><AccountHeader/><main className={`account-hub${section!=='hub'?' account-hub--page':''}`}>{content}</main></div>}
