import React,{createContext,useContext,useMemo,useState}from'react'
import{Link,NavLink,Route,Routes,useLocation,useNavigate,useParams}from'react-router-dom'
import{Accessibility,ArrowLeft,ArrowRight,Award,BadgePercent,Bell,CarFront,Check,ChevronDown,ChevronRight,CircleUserRound,CreditCard,Gift,Grid2X2,Heart,HelpCircle,Home,Info,Leaf,LogOut,MapPin,Martini,Menu,Minus,Navigation,PackageCheck,Phone,Plus,Search,ShieldCheck,Shirt,ShoppingBag,ShoppingBasket,SlidersHorizontal,Sparkles,SprayCan,Star,Store,UsersRound,X}from'lucide-react'
import mainStore from'./assets/main-store.webp'
import mainStore2 from'./assets/main-store2.webp'
import extraStore from'./assets/extra-store.webp'
import extraStore2 from'./assets/extra-store2.webp'
import storefrontDay from'./assets/storefront-day.webp'
import storefrontNight from'./assets/storefront-night.webp'
import lemonade24k from'./assets/24K-Lemonade-1.png'
import blackberryBreeze from'./assets/Blackberry-Breeze-Photoroom-1-900x900.png'
import blueberryYumYum from'./assets/Blueberry-Yum-Yum-1-Photoroom-900x900.png'
import spaceCadet from'./assets/Moonlight-Space-Cadet-5mg-THC-Live-Resin-1024x1024.png'
import pushPop from'./assets/Push-Pop-Photoroom-900x900.png'
import strawberryBanana from'./assets/Strawberry-Banana-Photoroom-900x900.png'
import strawberryLime from'./assets/Strawberry-Lime-Fusion-Photoroom-900x900.png'
import watermelonRefresher from'./assets/Watermelon-Refresher-Photoroom-900x900.png'
import mainstreetHoodie from'./assets/Lagom-Mainstreet-Hooded-Sweatshirt-900x900.png'
import midweightCrewneck from'./assets/Lagom-Midweight-Crewneck-Sweatshirt-Front-900x900.png'

const products=[
{id:'24k-lemonade',brand:'Lagom Naturals',name:'24K Lemonade',category:'Beverages',price:6,strength:'THC infused',type:'Seltzer',rating:4.9,reviews:124,weight:'12 oz',image:lemonade24k},
{id:'blackberry-breeze',brand:'Lagom Naturals',name:'Blackberry Breeze',category:'Beverages',price:6,strength:'THC infused',type:'Seltzer',rating:4.8,reviews:98,weight:'12 oz',image:blackberryBreeze},
{id:'strawberry-lime-fusion',brand:'Lagom Naturals',name:'Strawberry Lime Fusion',category:'Beverages',price:6,strength:'THC infused',type:'Seltzer',rating:4.8,reviews:83,weight:'12 oz',image:strawberryLime},
{id:'watermelon-refresher',brand:'Lagom Naturals',name:'Watermelon Refresher',category:'Beverages',price:6,strength:'THC infused',type:'Seltzer',rating:4.7,reviews:76,weight:'12 oz',image:watermelonRefresher},
{id:'blueberry-yum-yum',brand:'Lagom Naturals',name:'Blueberry Yum Yum',category:'Edibles',price:24.99,strength:'5mg THC + 20mg CBD',type:'Indica gummies',rating:4.9,reviews:151,weight:'10 pc',image:blueberryYumYum},
{id:'push-pop',brand:'Lagom Naturals',name:'Push Pop',category:'Edibles',price:24.99,strength:'5mg THC',type:'Hybrid gummies',rating:4.8,reviews:91,weight:'10 pc',image:pushPop},
{id:'space-cadet',brand:'Moonlight Cannabis',name:'Space Cadet',category:'Edibles',price:null,strength:'5mg THC',type:'Live resin',rating:4.8,reviews:64,weight:'See package',image:spaceCadet},
{id:'strawberry-banana',brand:'In-store selection',name:'Strawberry Banana',category:'Edibles',price:null,strength:'See package',type:'Cannabis edible',rating:4.7,reviews:64,weight:'See package',image:strawberryBanana}]
const merch=[
{id:'mainstreet-hoodie',name:'Mainstreet Hooded Sweatshirt',price:68,type:'Hoodies',image:mainstreetHoodie},
{id:'midweight-crewneck',name:'Midweight Crewneck Sweatshirt',price:58,type:'Crewnecks',image:midweightCrewneck}]
const categories=[['Flower',Leaf],['Vapes',SprayCan],['Edibles',Sparkles],['Pre-Rolls',PackageCheck],['Concentrates',Grid2X2],['Beverages',Martini],['Topicals',ShieldCheck],['Tinctures',Gift],['Accessories',ShoppingBag],['Apparel & Merch',Shirt],['Brands',Award],['Deals',BadgePercent]]

const Cart=createContext(null)
const useCart=()=>useContext(Cart)
function CartProvider({children}){const[items,setItems]=useState([{...products[0],qty:1},{...products[4],qty:1}]);const add=item=>{if(item.price==null)return;setItems(a=>{const f=a.find(x=>x.id===item.id);return f?a.map(x=>x.id===item.id?{...x,qty:x.qty+1}:x):[...a,{...item,qty:1}]})};const change=(id,qty)=>setItems(a=>a.map(x=>x.id===id?{...x,qty:Math.max(1,qty)}:x));const remove=id=>setItems(a=>a.filter(x=>x.id!==id));const count=items.reduce((n,x)=>n+x.qty,0);const subtotal=items.reduce((n,x)=>n+(x.price||0)*x.qty,0);return <Cart.Provider value={{items,add,change,remove,count,subtotal}}>{children}</Cart.Provider>}
function Logo({compact=false}){return <Link to="/" className={`brand ${compact?'compact':''}`}><img src="/lagom-logo.svg" alt="Lagom Naturals"/></Link>}
function Header(){const{count}=useCart();const[open,setOpen]=useState(false);return <><header><div className="shell header-inner"><button className="icon mobile" onClick={()=>setOpen(true)} aria-label="Menu"><Menu/></button><Logo compact/><nav className="desktop-nav"><NavLink to="/shop">Shop</NavLink><NavLink to="/merch">Merch</NavLink><NavLink to="/visit">Visit Us</NavLink><NavLink to="/about">About</NavLink></nav><div className="header-actions"><Link className="icon" to="/shop" aria-label="Search products"><Search/></Link><Link className="icon desktop" to="/account" aria-label="Account"><CircleUserRound/></Link><Link className="icon cart" to="/cart" aria-label={`Cart with ${count} items`}><ShoppingBag/>{count>0&&<b>{count}</b>}</Link></div></div></header>{open&&<div className="drawer-bg" onClick={()=>setOpen(false)}><aside className="drawer" onClick={e=>e.stopPropagation()}><div className="drawer-head"><Logo compact/><button className="icon" onClick={()=>setOpen(false)} aria-label="Close menu"><X/></button></div>{[['Shop','/shop'],['Apparel & Merch','/merch'],['Visit Our Store','/visit'],['About Lagom','/about'],['My Account','/account']].map(([a,b])=><Link key={b} to={b} onClick={()=>setOpen(false)}>{a}<ChevronRight/></Link>)}<div className="drawer-note"><MapPin/><span><b>North Loop Minneapolis</b><small>730 N Washington Ave</small></span></div></aside></div>}</>}
function MobileNav(){return <nav className="mobile-nav"><NavLink to="/"><Home/><span>Home</span></NavLink><NavLink to="/shop"><ShoppingBag/><span>Shop</span></NavLink><NavLink to="/account"><CircleUserRound/><span>Account</span></NavLink></nav>}
function Footer(){return <footer><div className="shell footer-grid"><div><Logo/><p>Premium cannabis from trusted brands, thoughtfully curated for a more balanced you.</p></div><div><h4>Shop</h4><Link to="/shop">All products</Link><Link to="/shop?category=Beverages">Beverages</Link><Link to="/shop?category=Edibles">Edibles</Link><Link to="/merch">Apparel & merch</Link></div><div><h4>Visit</h4><Link to="/visit">North Loop store</Link><span>730 N Washington Ave</span><span>Minneapolis, MN 55401</span></div><div><h4>Lagom</h4><Link to="/about">About us</Link><Link to="/account">Rewards</Link><Link to="/account">My account</Link></div></div><div className="shell footer-bottom"><span>© 2026 Lagom Naturals</span><span>For adults 21+. Please enjoy responsibly.</span></div></footer>}
function Layout({children}){return <div><Header/><main>{children}</main><Footer/><MobileNav/></div>}

function ProductCard({p}){const{add}=useCart();return <article className="product-card"><Link className="product-media real-product-media" to={`/product/${p.id}`}><img src={p.image} alt={`${p.brand} ${p.name}`} loading="lazy" decoding="async"/><button className="heart" onClick={e=>e.preventDefault()} aria-label={`Save ${p.name}`}><Heart/></button></Link><div className="product-info"><p>{p.brand}</p><Link to={`/product/${p.id}`}><h3>{p.name}</h3></Link><div className="rating"><Star fill="currentColor"/>{p.rating}<span>({p.reviews})</span></div><div className="tags"><span>{p.type}</span><span>{p.strength}</span></div><div className="product-foot"><span>{p.price!=null?<><b>${p.price.toFixed(2)}</b><small>{p.weight}</small></>:<><b>In-store</b><small>{p.weight}</small></>}</span>{p.price!=null?<button onClick={()=>add(p)} aria-label={`Add ${p.name} to cart`}><Plus/></button>:<Link className="product-details-link" to={`/product/${p.id}`}>Details</Link>}</div></div></article>}
function HomePage(){return <Layout><section className="hero shell"><div className="hero-media"><img src={mainStore} alt="Lagom Naturals dispensary interior" fetchPriority="high" decoding="async"/></div><div className="hero-card"><span className="location"><MapPin/> Minneapolis cannabis dispensary</span><h1>Find what feels <em>just right.</em></h1><p>Shop a thoughtfully curated mix of cannabis from trusted brands—clear choices, knowledgeable guidance, and the right fit for your routine.</p><div className="actions"><Link className="btn primary" to="/shop">Shop products <ArrowRight/></Link><Link className="btn secondary" to="/visit">Visit our store</Link></div></div></section><section className="shell trust"><div><Store/><span><b>Locally owned</b><small>North Loop roots</small></span></div><div><UsersRound/><span><b>Knowledgeable staff</b><small>Guidance without pressure</small></span></div><div><Heart/><span><b>Community focused</b><small>A better neighborhood shop</small></span></div></section><section className="section shell"><Title eyebrow="Explore the menu" title="Shop by category" to="/shop"/><div className="category-grid">{categories.slice(0,8).map(([n,I])=><Link className="category" to={`/shop?category=${encodeURIComponent(n)}`} key={n}><span><I/></span>{n}</Link>)}</div></section><section className="section shell"><Title eyebrow="Real products, real packaging" title="Featured products" to="/shop"/><div className="product-grid">{products.slice(0,4).map(p=><ProductCard p={p} key={p.id}/>)}</div></section><section className="shell story"><div className="story-img"><img src={mainStore2} alt="Lagom Naturals retail floor and customer experience" loading="lazy" decoding="async"/></div><div><p className="eyebrow">The Lagom approach</p><h2>Better choices start with better guidance.</h2><p>Lagom means “just the right amount.” We bring that idea into the retail experience: a considered menu, helpful people, and enough information to make a confident choice without making cannabis feel complicated.</p><div className="story-points"><span><ShieldCheck/><b>Curated brands</b><small>Selected for quality, consistency, and fit.</small></span><span><UsersRound/><b>Human guidance</b><small>Ask questions. Compare options. Take your time.</small></span></div><Link className="text-link" to="/about">Learn about Lagom <ArrowRight/></Link></div></section><section className="visit-band"><div className="shell visit-band-inner"><div><p className="eyebrow">Visit our store</p><h2>North Loop, Minneapolis</h2><p>730 N Washington Ave · Minneapolis, MN 55401</p></div><div className="actions"><Link className="btn light" to="/visit">Store details</Link><a className="btn outline" href="https://maps.google.com/?q=730+N+Washington+Ave+Minneapolis+MN+55401" target="_blank" rel="noreferrer">Get directions</a></div></div></section></Layout>}
function Title({eyebrow,title,to}){return <div className="section-head"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div><Link to={to}>View all <ArrowRight/></Link></div>}
function ShopPage(){const loc=useLocation();const init=new URLSearchParams(loc.search).get('category')||'All';const[category,setCategory]=useState(init);const[q,setQ]=useState('');const[sort,setSort]=useState('Featured');const cats=['All',...new Set(products.map(p=>p.category))];const visible=useMemo(()=>products.filter(p=>(category==='All'||p.category===category)&&`${p.brand} ${p.name}`.toLowerCase().includes(q.toLowerCase())).sort((a,b)=>sort==='Price: Low to High'?(a.price??Infinity)-(b.price??Infinity):sort==='Price: High to Low'?(b.price??-1)-(a.price??-1):b.rating-a.rating),[category,q,sort]);return <Layout><div className="page shell"><div className="page-title"><p className="eyebrow">Shop Lagom</p><h1>Cannabis, curated for balance.</h1><p>Browse the real products represented by the photography in our current catalog.</p></div><div className="search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search products or brands"/><SlidersHorizontal/></div><div className="toolbar"><div className="chips">{cats.map(c=><button className={category===c?'active':''} onClick={()=>setCategory(c)} key={c}>{c}</button>)}</div><select value={sort} onChange={e=>setSort(e.target.value)}><option>Featured</option><option>Price: Low to High</option><option>Price: High to Low</option></select></div><div className="listing-head"><h2>{category==='All'?'All products':category} <span>({visible.length})</span></h2></div><div className="product-grid listing">{visible.map(p=><ProductCard p={p} key={p.id}/>)}</div></div></Layout>}
function ProductPage(){const{id}=useParams();const p=products.find(x=>x.id===id)||products[0];const{add}=useCart();const[qty,setQty]=useState(1);return <Layout><div className="page shell"><Link className="back" to="/shop"><ArrowLeft/> Back to shop</Link><div className="detail real-product-detail"><div className="detail-media real-detail-media"><img src={p.image} alt={`${p.brand} ${p.name}`} fetchPriority="high" decoding="async"/></div><div className="detail-copy"><p className="brand-line">{p.brand}</p><h1>{p.name}</h1><div className="rating big"><Star fill="currentColor"/>{p.rating}<span>({p.reviews} reviews)</span></div><div className="price">{p.price!=null?`$${p.price.toFixed(2)}`:'Available in store'}</div><div className="tags large"><span>{p.type}</span><span>{p.strength}</span></div><p className="description">Product details, potency, batch information, and availability can vary. Review the package and current store information before purchase.</p><div className="qty-line"><b>Quantity</b><div className="qty"><button onClick={()=>setQty(Math.max(1,qty-1))}><Minus/></button><span>{qty}</span><button onClick={()=>setQty(qty+1)}><Plus/></button></div></div>{p.price!=null?<button className="btn primary full" onClick={()=>{for(let i=0;i<qty;i++)add(p)}}>Add to cart · ${(p.price*qty).toFixed(2)}</button>:<Link className="btn primary full" to="/visit">Check in-store availability</Link>}<div className="accordions"><details open><summary>Product details <ChevronDown/></summary><p>Category: {p.category}. Type: {p.type}. Potency: {p.strength}. Inventory and batch details may vary.</p></details><details><summary>Pickup information <ChevronDown/></summary><p>Availability is confirmed at pickup. Product imagery represents the packaged product currently featured on this site.</p></details><details><summary>Responsible use <ChevronDown/></summary><p>For adults 21+. Start low, go slow, and keep cannabis away from children and pets.</p></details></div></div></div></div></Layout>}
function MerchPage(){const[f,setF]=useState('All');const filters=['All',...new Set(merch.map(m=>m.type))];return <Layout><div className="page shell"><div className="editorial"><p className="eyebrow">Lagom originals</p><h1>Apparel & merch</h1><p>Real Lagom apparel, shown with the product photography in our catalog.</p></div><div className="chips centered">{filters.map(x=><button className={f===x?'active':''} onClick={()=>setF(x)} key={x}>{x}</button>)}</div><div className="merch-grid real-merch-grid">{merch.filter(m=>f==='All'||m.type===f).map(m=><article className="merch-card" key={m.id}><div className="merch-media real-merch-media"><img src={m.image} alt={`Lagom Naturals ${m.name}`} loading="lazy" decoding="async"/></div><div><p>Lagom Naturals</p><h3>{m.name}</h3><b>${m.price.toFixed(2)}</b><small className="merch-type">{m.type}</small></div></article>)}</div></div></Layout>}
function CartPage(){const{items,change,remove,subtotal}=useCart();const nav=useNavigate();const tax=subtotal*.08;return <Layout><div className="page shell narrow"><h1 className="cart-title">Your cart <span>({items.length})</span></h1><div className="cart-layout"><div className="cart-list">{items.map(x=><div className="cart-row" key={x.id}><div className="cart-thumb real-cart-thumb"><img src={x.image} alt="" loading="lazy" decoding="async"/></div><div className="cart-info"><p>{x.brand}</p><b>{x.name}</b><small>{x.weight}</small><div className="qty small"><button onClick={()=>change(x.id,x.qty-1)}><Minus/></button><span>{x.qty}</span><button onClick={()=>change(x.id,x.qty+1)}><Plus/></button></div></div><div className="cart-price"><b>${((x.price||0)*x.qty).toFixed(2)}</b><button onClick={()=>remove(x.id)}>Remove</button></div></div>)}</div><aside className="summary"><label>Add a note (optional)<textarea placeholder="Pickup notes or product questions"/></label><Line a="Subtotal" b={`$${subtotal.toFixed(2)}`}/><Line a="Estimated taxes" b={`$${tax.toFixed(2)}`}/><Line a="Estimated total" b={`$${(subtotal+tax).toFixed(2)}`} total/><div className="pickup"><Store/><span><b>Pickup at Lagom Naturals</b><small>Usually ready in 1–2 hours</small></span></div><button className="btn primary full" onClick={()=>nav('/checkout')}>Proceed to checkout</button></aside></div></div></Layout>}
function Line({a,b,total=false}){return <div className={`summary-line ${total?'total':''}`}><span>{a}</span><b>{b}</b></div>}
function CheckoutPage(){const{subtotal}=useCart();const[step,setStep]=useState(1);const[done,setDone]=useState(false);if(done)return <Layout><div className="page shell success"><div><Check/></div><p className="eyebrow">Order received</p><h1>We’ll have it ready.</h1><p>Your pickup order has been placed. We’ll send an update when it’s ready at our North Loop store.</p><Link className="btn primary" to="/account">View my orders</Link></div></Layout>;return <Layout><div className="page shell checkout"><h1>Checkout</h1><div className="steps"><span className={step>=1?'active':''}>1 <b>Contact</b></span><i/><span className={step>=2?'active':''}>2 <b>Payment</b></span><i/><span className={step>=3?'active':''}>3 <b>Review</b></span></div>{step===1&&<div className="checkout-panel"><h2>Contact information</h2><label>Email address<input defaultValue="jordan@example.com"/></label><label className="check"><input type="checkbox" defaultChecked/> Send me order updates</label><h2>Fulfillment method</h2><div className="radio-card"><Store/><span><b>Store pickup</b><small>Pickup at our Minneapolis location</small></span></div><div className="location-card"><b>Lagom Naturals</b><span>730 N Washington Ave<br/>Minneapolis, MN 55401</span></div><button className="btn primary full" onClick={()=>setStep(2)}>Continue to payment</button></div>}{step===2&&<div className="checkout-panel"><h2>Payment</h2><label>Card number<input placeholder="1234 5678 9012 3456"/></label><div className="split"><label>Expiration<input placeholder="MM / YY"/></label><label>CVC<input placeholder="123"/></label></div><label>Name on card<input placeholder="Jordan Lee"/></label><button className="btn primary full" onClick={()=>setStep(3)}>Review order</button></div>}{step===3&&<div className="checkout-panel"><h2>Review your order</h2><div className="location-card"><span>Pickup</span><b>Lagom Naturals · North Loop</b><small>730 N Washington Ave, Minneapolis</small></div><Line a="Estimated total" b={`$${(subtotal*1.08).toFixed(2)}`} total/><button className="btn primary full" onClick={()=>setDone(true)}>Place pickup order</button></div>}</div></Layout>}
function AccountPage(){const rows=[[PackageCheck,'My Orders'],[Heart,'Favorites'],[MapPin,'Addresses'],[CreditCard,'Payment Methods']];const lower=[[SlidersHorizontal,'Account Settings'],[Bell,'Notifications'],[HelpCircle,'Help & Support']];return <Layout><div className="page shell account"><div className="account-hero"><Leaf/><span><p>Welcome back,</p><h1>Jordan</h1></span></div><div className="account-list">{rows.map(([I,n])=><button key={n}><I/><span>{n}</span><ChevronRight/></button>)}<button className="rewards"><Gift/><span><b>Rewards</b><small>Shop. Earn. Get more.</small></span><ChevronRight/></button>{lower.map(([I,n])=><button key={n}><I/><span>{n}</span><ChevronRight/></button>)}<button className="signout"><LogOut/><span>Sign Out</span></button></div></div></Layout>}
function VisitPage(){return <Layout><div><section className="visit-hero"><img src={storefrontDay} alt="Lagom Naturals storefront in Minneapolis" fetchPriority="high" decoding="async"/><div className="visit-card shell"><p className="eyebrow">Visit our store</p><h1>North Loop<br/>Minneapolis</h1><p>730 N Washington Ave<br/>Minneapolis, MN 55401</p><div className="actions"><a className="btn primary" href="https://maps.google.com/?q=730+N+Washington+Ave+Minneapolis+MN+55401" target="_blank" rel="noreferrer"><Navigation/> Get directions</a><a className="btn secondary" href="tel:+16125550101"><Phone/> Call store</a></div></div></section><section className="shell visit-details"><div className="hours"><h2>Store hours</h2><span>Mon – Sat<b>10:00 AM – 9:00 PM</b></span><span>Sunday<b>11:00 AM – 6:00 PM</b></span><div className="amenities"><span><CarFront/>Parking nearby</span><span><ShoppingBasket/>In-store pickup</span><span><Accessibility/>Accessible entrance</span></div></div><div className="gallery"><img src={extraStore} alt="Lagom Naturals interior display and retail environment" loading="lazy" decoding="async"/><img src={extraStore2} alt="Lagom Naturals store interior" loading="lazy" decoding="async"/><img src={mainStore2} alt="Lagom Naturals retail floor" loading="lazy" decoding="async"/></div></section></div></Layout>}
function AboutPage(){return <Layout><section className="shell about-hero"><div><p className="eyebrow">About Lagom Naturals</p><h1>Enough choice. More clarity. Better balance.</h1><p>Lagom is a Swedish idea meaning “not too much, not too little—just right.” For us, it is a practical standard for how a dispensary should feel.</p></div><img src={extraStore2} alt="Inside Lagom Naturals in Minneapolis" fetchPriority="high" decoding="async"/></section><section className="shell principles"><article><span>01</span><h2>Retailer first</h2><p>We are a multi-brand cannabis storefront. Our role is to curate, compare, explain, and make great products easier to shop.</p></article><article><span>02</span><h2>Knowledge without theater</h2><p>Helpful staff, straightforward information, and a premium experience that never becomes intimidating.</p></article><article><span>03</span><h2>Rooted in Minneapolis</h2><p>Designed for the North Loop and built to be part of the neighborhood, not just another transactional storefront.</p></article></section><div className="about-photo"><img src={storefrontNight} alt="Lagom Naturals North Loop storefront at night" loading="lazy" decoding="async"/></div></Layout>}
function NotFound(){return <Layout><div className="page shell empty"><Info/><h1>Page not found</h1><p>The page you’re looking for isn’t here.</p><Link className="btn primary" to="/">Back home</Link></div></Layout>}
export default function App(){return <CartProvider><Routes><Route path="/" element={<HomePage/>}/><Route path="/shop" element={<ShopPage/>}/><Route path="/product/:id" element={<ProductPage/>}/><Route path="/merch" element={<MerchPage/>}/><Route path="/cart" element={<CartPage/>}/><Route path="/checkout" element={<CheckoutPage/>}/><Route path="/account" element={<AccountPage/>}/><Route path="/visit" element={<VisitPage/>}/><Route path="/about" element={<AboutPage/>}/><Route path="*" element={<NotFound/>}/></Routes></CartProvider>}
