import React,{createContext,useContext,useMemo,useState}from'react'
import{Link,NavLink,Route,Routes,useLocation,useNavigate,useParams}from'react-router-dom'
import{ArrowLeft,ArrowRight,ChevronDown,ChevronRight,CircleHelp,CircleUserRound,CreditCard,Gift,Heart,Home,MapPin,Menu,Minus,Navigation,PackageCheck,Phone,Plus,Search,Settings,Share2,ShoppingBag,SlidersHorizontal,Star,Store,Truck,UsersRound,X}from'lucide-react'
import mainStore from'./assets/main-store.webp'
import mainStore2 from'./assets/main-store2.webp'
import extraStore from'./assets/extra-store.webp'
import extraStore2 from'./assets/extra-store2.webp'
import storefrontDay from'./assets/storefront-day.webp'
import storefrontNight from'./assets/storefront-night.webp'
import lemonade24k from'./assets/24K-Lemonade-1.png'
import blackberryBreeze from'./assets/Blackberry-Breeze-Photoroom-1-900x900.png'
import blueberryYumYum from'./assets/Blueberry-Yum-Yum-1-Photoroom-900x900.png'
import spaceCadet from'./assets/Moonlight-Space-Cadet-5mg-THC-Live-Resin-1024x1024.png'
import pushPop from'./assets/Push-Pop-Photoroom-900x900.png'
import strawberryBanana from'./assets/Strawberry-Banana-Photoroom-900x900.png'
import strawberryLime from'./assets/Strawberry-Lime-Fusion-Photoroom-900x900.png'
import watermelonRefresher from'./assets/Watermelon-Refresher-Photoroom-900x900.png'
import mainstreetHoodie from'./assets/Lagom-Mainstreet-Hooded-Sweatshirt-900x900.png'
import midweightCrewneck from'./assets/Lagom-Midweight-Crewneck-Sweatshirt-Front-900x900.png'

const products=[
{id:'24k-lemonade',brand:'Lagom Naturals',name:'24K Lemonade',category:'Beverages',price:6,strength:'THC infused',type:'Seltzer',rating:4.9,reviews:124,weight:'12 oz',image:lemonade24k},
{id:'blackberry-breeze',brand:'Lagom Naturals',name:'Blackberry Breeze',category:'Beverages',price:6,strength:'THC infused',type:'Seltzer',rating:4.8,reviews:98,weight:'12 oz',image:blackberryBreeze},
{id:'strawberry-lime-fusion',brand:'Lagom Naturals',name:'Strawberry Lime Fusion',category:'Beverages',price:6,strength:'THC infused',type:'Seltzer',rating:4.8,reviews:83,weight:'12 oz',image:strawberryLime},
{id:'watermelon-refresher',brand:'Lagom Naturals',name:'Watermelon Refresher',category:'Beverages',price:6,strength:'THC infused',type:'Seltzer',rating:4.7,reviews:76,weight:'12 oz',image:watermelonRefresher},
{id:'blueberry-yum-yum',brand:'Lagom Naturals',name:'Blueberry Yum Yum',category:'Edibles',price:24.99,strength:'5mg THC + 20mg CBD',type:'Indica gummies',rating:4.9,reviews:151,weight:'10 pc',image:blueberryYumYum},
{id:'push-pop',brand:'Lagom Naturals',name:'Push Pop',category:'Edibles',price:24.99,strength:'5mg THC',type:'Hybrid gummies',rating:4.8,reviews:91,weight:'10 pc',image:pushPop},
{id:'space-cadet',brand:'Moonlight Cannabis',name:'Space Cadet',category:'Edibles',price:null,strength:'5mg THC',type:'Live resin',rating:4.8,reviews:64,weight:'See package',image:spaceCadet},
{id:'strawberry-banana',brand:'In-store selection',name:'Strawberry Banana',category:'Edibles',price:null,strength:'See package',type:'Cannabis edible',rating:4.7,reviews:64,weight:'See package',image:strawberryBanana}]
const merch=[
{id:'mainstreet-hoodie',name:'Mainstreet Hooded Sweatshirt',price:68,type:'Hoodies',color:'Black',image:mainstreetHoodie},
{id:'midweight-crewneck',name:'Midweight Crewneck Sweatshirt',price:58,type:'Crewnecks',color:'Sand',image:midweightCrewneck}]
const categoryCards=[
['Flower','Flower'],['Vapes','Vapes'],['Edibles','Edibles'],['Pre-Rolls','Pre-Rolls'],['Concentrates','Concentrates'],['Beverages','Beverages'],['Topicals','Topicals'],['Tinctures','Tinctures'],['Accessories','Accessories'],['Apparel & Merch','Merch'],['Brands','Brands'],['Deals','Deals']]
const categoryImages={Edibles:blueberryYumYum,Beverages:lemonade24k,'Apparel & Merch':mainstreetHoodie}

const Cart=createContext(null)
const useCart=()=>useContext(Cart)
function CartProvider({children}){const[items,setItems]=useState([{...products[0],qty:1},{...products[4],qty:1},{...merch[1],brand:'Lagom Naturals',weight:'M · Sand',category:'Merch',qty:1}]);const add=item=>{if(item.price==null)return;setItems(a=>{const f=a.find(x=>x.id===item.id);return f?a.map(x=>x.id===item.id?{...x,qty:x.qty+1}:x):[...a,{...item,qty:1}]})};const change=(id,qty)=>setItems(a=>a.map(x=>x.id===id?{...x,qty:Math.max(1,qty)}:x));const remove=id=>setItems(a=>a.filter(x=>x.id!==id));const count=items.reduce((n,x)=>n+x.qty,0);const subtotal=items.reduce((n,x)=>n+(x.price||0)*x.qty,0);return <Cart.Provider value={{items,add,change,remove,count,subtotal}}>{children}</Cart.Provider>}

function Logo(){return <Link to="/" className="brand"><img src="/lagom-logo.svg" alt="Lagom Naturals"/></Link>}
function Header({detail=false}){const{count}=useCart();const[open,setOpen]=useState(false);const nav=useNavigate();return <><header className="site-header"><div className="header-inner">{detail?<button className="icon-btn" onClick={()=>nav(-1)} aria-label="Back"><ArrowLeft/></button>:<button className="icon-btn" onClick={()=>setOpen(true)} aria-label="Menu"><Menu/></button>}<Logo/><div className="header-tools">{detail&&<button className="icon-btn" aria-label="Share"><Share2/></button>}<Link className="icon-btn" to="/shop" aria-label="Search"><Search/></Link>{!detail&&<Link className="icon-btn cart-icon" to="/cart" aria-label="Cart"><ShoppingBag/>{count>0&&<b>{count}</b>}</Link>}{detail&&<button className="icon-btn" aria-label="Save"><Heart/></button>}</div></div></header>{open&&<div className="drawer-bg" onClick={()=>setOpen(false)}><aside className="drawer" onClick={e=>e.stopPropagation()}><div className="drawer-top"><Logo/><button className="icon-btn" onClick={()=>setOpen(false)}><X/></button></div>{[['Shop','/shop'],['Apparel & Merch','/merch'],['Visit Our Store','/visit'],['About Lagom','/about'],['My Account','/account']].map(([a,b])=><Link key={b} to={b} onClick={()=>setOpen(false)}>{a}<ChevronRight/></Link>)}</aside></div>}</>}
function MobileNav(){return <nav className="mobile-nav"><NavLink to="/"><Home/><span>Home</span></NavLink><NavLink to="/shop"><ShoppingBag/><span>Shop</span></NavLink><NavLink to="/account"><CircleUserRound/><span>Account</span></NavLink></nav>}
function Shell({children,detail=false,noNav=false}){return <div className="app-shell"><Header detail={detail}/><main>{children}</main>{!noNav&&<MobileNav/>}</div>}

function SectionTitle({title,to='/shop'}){return <div className="section-title"><h2>{title}</h2><Link to={to}>View All <ArrowRight/></Link></div>}
function CategoryCard({name,label}){const img=categoryImages[name];return <Link className="category-card" to={name==='Apparel & Merch'?'/merch':`/shop?category=${encodeURIComponent(name)}`}>{img?<img src={img} alt=""/>:<div className="category-symbol">{label.slice(0,2).toUpperCase()}</div>}<span>{label}</span></Link>}
function ProductCard({p}){const{add}=useCart();return <article className="product-card"><Link className="product-media" to={`/product/${p.id}`}><img src={p.image} alt={`${p.brand} ${p.name}`} loading="lazy"/><button className="heart-btn" onClick={e=>e.preventDefault()} aria-label="Save"><Heart/></button></Link><div className="product-copy"><p>{p.brand}</p><Link to={`/product/${p.id}`}><h3>{p.name}</h3></Link><small>{p.type} · {p.strength}</small><div className="stars"><Star fill="currentColor"/><span>{p.rating}</span><em>({p.reviews})</em></div><b>{p.price==null?'In-store':`$${p.price.toFixed(2)}`}</b>{p.price!=null&&<div className="card-actions"><button>{p.weight}<ChevronDown/></button><button className="add-square" onClick={()=>add(p)} aria-label={`Add ${p.name}`}><Plus/></button></div>}</div></article>}

function HomePage(){return <Shell><section className="home-hero"><img src={mainStore} alt="Lagom Naturals dispensary interior" fetchPriority="high"/><div className="hero-gradient"/><div className="hero-copy"><p>MINNEAPOLIS CANNABIS DISPENSARY</p><h1>Find Your<br/>Just Right.</h1><span>Premium cannabis products from trusted brands. Thoughtfully curated for a more balanced you — right here in Minneapolis.</span><div className="hero-actions"><Link to="/shop">SHOP PRODUCTS <ArrowRight/></Link><Link to="/visit">VISIT OUR STORE</Link></div></div></section><section className="trust-strip"><div><Store/><span>LOCALLY<br/>OWNED</span></div><div><UsersRound/><span>KNOWLEDGEABLE<br/>STAFF</span></div><div><Heart/><span>COMMUNITY<br/>FOCUSED</span></div></section><section className="mobile-section"><SectionTitle title="Shop by Category"/><div className="home-category-row">{categoryCards.slice(0,4).map(([a,b])=><CategoryCard key={a} name={a} label={b}/>)}</div></section><section className="mobile-section"><SectionTitle title="Featured Products"/><div className="product-grid">{products.slice(0,4).map(p=><ProductCard key={p.id} p={p}/>)}</div></section></Shell>}

function ShopPage(){const loc=useLocation();const category=new URLSearchParams(loc.search).get('category');if(category)return <ListingPage category={category}/>;return <Shell><div className="shop-page"><div className="shop-search"><Search/><input placeholder="Search products, brands, or effects..."/></div><div className="category-grid">{categoryCards.map(([a,b])=><CategoryCard key={a} name={a} label={b}/>)}</div><Link className="originals-banner" to="/merch"><img src={midweightCrewneck} alt="Lagom Originals"/><span>Lagom Originals</span><ChevronRight/></Link><SectionTitle title="Featured Products"/><div className="product-grid">{products.slice(0,4).map(p=><ProductCard key={p.id} p={p}/>)}</div></div></Shell>}
function ListingPage({category}){const[filter,setFilter]=useState('All');const visible=products.filter(p=>category==='All'||p.category===category);return <Shell><div className="listing-page"><h1>{category} <span>({visible.length||142})</span></h1><div className="filter-row"><button><SlidersHorizontal/> Filter</button><button>↕ Sort</button></div><div className="chips"><button className={filter==='All'?'active':''} onClick={()=>setFilter('All')}>All</button><button onClick={()=>setFilter('Indica')}>Indica</button><button onClick={()=>setFilter('Sativa')}>Sativa</button><button onClick={()=>setFilter('Hybrid')}>Hybrid</button></div><div className="product-grid listing-grid">{(visible.length?visible:products).map(p=><ProductCard key={p.id} p={p}/>)}</div></div></Shell>}

function ProductPage(){const{id}=useParams();const p=products.find(x=>x.id===id)||products[0];const{add}=useCart();const[qty,setQty]=useState(1);return <Shell detail><div className="pdp"><div className="pdp-media"><img src={p.image} alt={`${p.brand} ${p.name}`}/><div className="pdp-dots"><i className="active"/><i/><i/><i/><i/></div></div><div className="pdp-copy"><p>{p.brand}</p><h1>{p.name}</h1><div className="review-line"><span>★★★★★</span> <small>({p.reviews} reviews)</small></div><h2>{p.price==null?'Available in store':`$${p.price.toFixed(2)}`}</h2><div className="meta-pills"><span>{p.type}</span><span>{p.strength}</span></div><p className="pdp-desc">Product details, potency, batch information, and availability can vary. Review current package information before purchase.</p>{p.price!=null&&<><label>Size</label><div className="size-row"><button className="active">{p.weight}</button><button>1/4 oz</button><button>1/2 oz</button><button>1 oz</button></div><div className="qty-row"><b>Quantity</b><div><button onClick={()=>setQty(Math.max(1,qty-1))}><Minus/></button><span>{qty}</span><button onClick={()=>setQty(qty+1)}><Plus/></button></div></div><button className="primary-bar" onClick={()=>{for(let i=0;i<qty;i++)add(p)}}>ADD TO CART</button></>}</div></div></Shell>}

function MerchPage(){return <Shell><div className="merch-page"><div className="merch-head"><h1>APPAREL & MERCH</h1><p>Wear the balance.</p></div><div className="chips merch-chips"><button className="active">All</button><button>Tees</button><button>Hoodies</button><button>Hats</button><button>Accessories</button></div><div className="merch-grid">{merch.map(m=><Link className="merch-card" key={m.id} to={`/merch/${m.id}`}><div className="merch-media"><img src={m.image} alt={m.name}/><Heart/></div><p>Lagom Naturals</p><h3>{m.name}</h3><b>${m.price.toFixed(2)}</b><div className="swatches"><i/><i/><i/></div></Link>)}</div></div></Shell>}
function MerchDetailPage(){const{id}=useParams();const m=merch.find(x=>x.id===id)||merch[0];const{add}=useCart();const[qty,setQty]=useState(1);return <Shell detail><div className="merch-detail"><div className="merch-detail-media"><img src={m.image} alt={m.name}/></div><p>Lagom Naturals</p><h1>{m.name}</h1><h2>${m.price.toFixed(2)}</h2><div className="option-line"><b>Color: {m.color}</b><div className="swatches large"><i/><i/><i/><i/></div></div><b className="option-label">Size</b><div className="size-row apparel"><button>S</button><button className="active">M</button><button>L</button><button>XL</button><button>XXL</button></div><div className="qty-row"><b>Quantity</b><div><button onClick={()=>setQty(Math.max(1,qty-1))}><Minus/></button><span>{qty}</span><button onClick={()=>setQty(qty+1)}><Plus/></button></div></div><button className="primary-bar" onClick={()=>{for(let i=0;i<qty;i++)add({...m,brand:'Lagom Naturals',weight:`M · ${m.color}`,category:'Merch'})}}>ADD TO CART</button>{['Product Details','Materials','Fit','Care','Shipping / Pickup'].map(x=><div className="detail-row" key={x}><span>{x}</span><ChevronDown/></div>)}</div></Shell>}

function CartPage(){const{items,change,remove,subtotal}=useCart();return <Shell><div className="cart-page"><h1>Your Cart <span>({items.length})</span></h1><div className="cart-list">{items.map(x=><div className="cart-row" key={x.id}><img src={x.image} alt=""/><div className="cart-item-copy"><p>{x.brand||'Lagom Naturals'}</p><b>{x.name}</b><small>{x.weight}</small></div><strong>${((x.price||0)*x.qty).toFixed(2)}</strong><div className="cart-qty"><button onClick={()=>change(x.id,x.qty-1)}><Minus/></button><span>{x.qty}</span><button onClick={()=>change(x.id,x.qty+1)}><Plus/></button></div><button className="remove" onClick={()=>remove(x.id)}>×</button></div>)}</div><textarea placeholder="Add a note (optional)"/><div className="totals"><p><span>Subtotal</span><b>${subtotal.toFixed(2)}</b></p><p><span>Estimated taxes</span><b>${(subtotal*.08).toFixed(2)}</b></p></div><div className="pickup-row"><span><b>Pickup at Lagom Naturals</b><small>Ready in 1–2 hours</small></span><button>Change</button></div><Link className="primary-bar linkbar" to="/checkout">PROCEED TO CHECKOUT</Link></div></Shell>}

function CheckoutPage(){const[step,setStep]=useState(1);return <Shell><div className="checkout-page"><h1>Checkout</h1><div className="checkout-steps"><span className={step>=1?'active':''}>1 <b>SHIPPING</b></span><i/><span className={step>=2?'active':''}>2 <b>PAYMENT</b></span><i/><span className={step>=3?'active':''}>3 <b>REVIEW</b></span></div>{step===1&&<><h2>Contact information</h2><label>Email address<input defaultValue="jordan@example.com"/></label><label className="checkbox"><input type="checkbox" defaultChecked/> Send me order updates</label><h2>Fulfillment method</h2><div className="method-card active"><Store/><span><b>Store Pickup</b><small>Pickup at our Minneapolis location</small></span></div><div className="method-card"><Truck/><span><b>Shipping</b><small>Where available</small></span></div><h2>Pickup location</h2><div className="pickup-card"><span><b>Lagom Naturals</b><small>730 N Washington Ave<br/>Minneapolis, MN 55401</small></span><button>Change</button></div><button className="primary-bar" onClick={()=>setStep(2)}>Continue to Payment</button></>}{step===2&&<><h2>Payment</h2><p className="muted">Payment UI placeholder only. No transaction rail is connected.</p><button className="primary-bar" onClick={()=>setStep(3)}>Continue to Review</button></>}{step===3&&<><h2>Review</h2><div className="pickup-card"><span><b>Store Pickup</b><small>Lagom Naturals · North Loop</small></span></div><Link className="primary-bar linkbar" to="/account">Finish</Link></>}</div></Shell>}

function AccountPage(){const rows=[[PackageCheck,'My Orders'],[Heart,'Favorites'],[MapPin,'Addresses'],[CreditCard,'Payment Methods']];const lower=[[Settings,'Account Settings'],[Gift,'Notifications'],[CircleHelp,'Help & Support']];return <Shell><div className="account-page"><div className="account-welcome"><div className="leaf-mark">⌁</div><span><p>Welcome back,</p><h1>Jordan</h1></span></div><div className="account-rows">{rows.map(([I,n])=><button key={n}><I/><span>{n}</span><ChevronRight/></button>)}<button className="reward-row"><Gift/><span><b>Rewards</b><small>Shop. Earn. Get more.</small></span><ChevronRight/></button>{lower.map(([I,n])=><button key={n}><I/><span>{n}</span><ChevronRight/></button>)}<button className="signout">Sign Out</button></div></div></Shell>}

function VisitPage(){return <Shell><div className="visit-page"><div className="visit-photo"><img src={storefrontDay} alt="Lagom Naturals storefront"/></div><div className="visit-card"><p>VISIT OUR STORE</p><h1>North Loop<br/>Minneapolis</h1><span>730 N Washington Ave<br/>Minneapolis, MN 55401</span><div className="visit-actions"><a href="https://maps.google.com/?q=730+N+Washington+Ave+Minneapolis+MN+55401" target="_blank" rel="noreferrer"><Navigation/> GET DIRECTIONS</a><a href="tel:+16125550101"><Phone/> CALL STORE</a></div><div className="hours"><b>Store Hours</b><p><span>Mon – Sat</span><strong>10:00 AM – 9:00 PM</strong></p><p><span>Sunday</span><strong>11:00 AM – 6:00 PM</strong></p></div><div className="amenities"><span>Parking<br/>Available</span><span>In-Store<br/>Pickup</span><span>Accessible<br/>Entrance</span></div></div></div></Shell>}
function AboutPage(){return <Shell><div className="about-page"><img src={mainStore2} alt="Inside Lagom Naturals"/><h1>Enough choice.<br/>More clarity.<br/>Better balance.</h1><p>Lagom is a Swedish idea meaning “not too much, not too little—just right.” We bring that standard to a multi-brand dispensary experience built around clear choices and thoughtful guidance.</p><div className="about-grid"><img src={extraStore} alt="Lagom Naturals interior"/><img src={extraStore2} alt="Lagom Naturals interior"/></div><img src={storefrontNight} alt="Lagom Naturals at night"/></div></Shell>}

export default function App(){return <CartProvider><Routes><Route path="/" element={<HomePage/>}/><Route path="/shop" element={<ShopPage/>}/><Route path="/product/:id" element={<ProductPage/>}/><Route path="/merch" element={<MerchPage/>}/><Route path="/merch/:id" element={<MerchDetailPage/>}/><Route path="/cart" element={<CartPage/>}/><Route path="/checkout" element={<CheckoutPage/>}/><Route path="/account" element={<AccountPage/>}/><Route path="/visit" element={<VisitPage/>}/><Route path="/about" element={<AboutPage/>}/><Route path="*" element={<HomePage/>}/></Routes></CartProvider>}
